### PR TITLE
try gulp with a retry

### PR DESCRIPTION
**Pull request by bigloser**

### CODE REVIEW

**Comment by bmangold** [comment]
It would be nice to do a syntax/compilation check and then do the retry , but this is def better than what we have , assuming a retry would correct things

**Comment by bigloser** [comment]
FYI I tried this out locally so syntax *should* be fine

**Comment by bigloser** [comment]
also this is a general retry function so compilation checks etc. might not fit in _this_ funciton

**Comment by bmangold** [comment]
oh, i mean, doing a compilation on the JS code prior to retry and abort if thats the case

**Comment by bmangold** [comment]
LGTM

**Pull request closed without merging**
